### ISSUE TITLE
Widget breaks sidebar items, doesn't close aside 

### ISSUE THREAD

**Issue by dryanmedia** [INN/DoubleClick-for-WordPress#11]
<img width="314" alt="screen shot 2015-12-14 at 2 57 13 pm" src="https://cloud.githubusercontent.com/assets/9565066/11798122/643526b8-a285-11e5-9a66-afe46c361961.png">

DFW Widget is wrapping all subsequent widgets within it's `<aside>`. =|
* Compared with Largo widgets for construction
* Converted Cornell Sun HP Right Rail to use standard `main-sidebar` and converted styles, adjusted for defaults
* Checked NPQ.org live version, which is functioning properly using a different version of widget but no maj/min version bump so short of comparing hashes, suffice to say it is older than `master` and what is on wp.org.
* When broken widget is active, breaks hard-coded ad placements
* Doesn't flip console errors.

Will be asking for a second pair of eyes on this one tmw.

**Comment by dryanmedia** [comment]
Fix in #12

**Comment by benlk** [comment]
#12 was merged; closing
