### ISSUE TITLE
Basic docs for DFP setup questions

### ISSUE THREAD

**Issue by benlk** [INN/DoubleClick-for-WordPress#21]
Where possible, link out to official DFP docs instead of rewriting them. Original INN-written docs should be reserved for plugin functionality or plugin-DFP integration tasks.

**Comment by benlk** [comment]
This is partly covered by the DfP/DfW training docs worked on by @jackbrighton in that Asana project. Once that's ready, we should copy as much of that as possible over to here, or link from here to wherever those docs end up living.

**Comment by aschweigert** [comment]
I would probably just add those to this repo, it's the best place for them to live given that this is the plugin we'd be using to do all of that stuff for our sites anyway
