### ISSUE TITLE
Missing setting option

### ISSUE THREAD

**Issue by karlosjunior** [INN/DoubleClick-for-WordPress#35]
I don't seem to have the settings so I cant place my identifier. I'm using Newspaper - Theme 7.5
![image](https://cloud.githubusercontent.com/assets/27176994/24843134/e3d2daa6-1df3-11e7-9dd0-08bab548a53f.png)

**Comment by benlk** [comment]
The settings page for DfW is under "Tools" in the main WordPress menu:

<img width="187" alt="screen shot 2017-04-10 at 10 25 24 am" src="https://cloud.githubusercontent.com/assets/1754187/24866437/1a531daa-1dd8-11e7-809a-51c577bebd03.png">

You can also find it at `example.com/wp-admin/options-general.php?page=doubleclick-for-wordpress`

**Comment by karlosjunior** [comment]
Thank you!
