### ISSUE TITLE
Run VIP code check, create issues for problems

### ISSUE THREAD

**Issue by benlk** [INN/DoubleClick-for-WordPress#40]
https://vip.wordpress.com/documentation/vip/code-and-theme-review-process/

- The plugin should not rely on the plugin activation and deactivation hooks as VIP plugins are a part of your theme and are loaded using require_once() rather than the plugins menu.
- Run WordPress' phpcs rules against it: https://make.wordpress.org/core/handbook/best-practices/coding-standards/
- Check https://vip.wordpress.com/documentation/vip/code-review-what-we-look-for/

Requested by @aschweigert for "a...friend"

**Comment by aschweigert** [comment]
**FILE: DoubleClick-for-WordPress/dfw-init.php**

- [ ] 6 | ERROR   | Variable "DoubleClick" is not in valid snake_case format
- [ ] 37 | ERROR   | Member variable "networkCode" is not in valid snake_case format.
- [ ] 59 | ERROR   | Member variable "adSlots" is not in valid snake_case format.
- [ ] 89 | ERROR   | Variable "networkCode" is not in valid snake_case format
- [ ] 91 | ERROR   | Object property "networkCode" is not in valid snake_case format
- [ ] 91 | ERROR   | Variable "networkCode" is not in valid snake_case format
- [ ] 151 | ERROR   | Object property "adSlots" is not in valid snake_case format
- [ ] 158 | ERROR   | Object property "networkCode" is not in valid snake_case format
- [ ] 181 | ERROR   | Method name "networkCode" in class DoubleClick is not in snake case format, try "network_code"
- [ ] 182 | ERROR   | Object property "networkCode" is not in valid snake_case format
- [ ] 182 | ERROR   | Object property "networkCode" is not in valid snake_case format
- [ ] 188 | ERROR   | Object property "adSlots" is not in valid snake_case format
- [ ] 195 | ERROR   | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$this'
- [ ] 283 | ERROR   | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$this'
- [ ] 283 | ERROR   | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$sizes'
- [ ] 283 | ERROR   | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$args'
- [ ]  289 | ERROR   | Use Yoda Condition checks, you must
- [ ] 299 | ERROR   | Variable "adObject" is not in valid snake_case format
- [ ] 300 | ERROR   | Object property "adSlots" is not in valid snake_case format
- [ ] 300 | ERROR   | Variable "adObject" is not in valid snake_case format
- [ ] 309 | ERROR   | Variable "adObject" is not in valid snake_case format
- [ ] 311 | ERROR   | Variable "adObject" is not in valid snake_case format
- [ ] 357 | ERROR   | Variable "DoubleClick" is not in valid snake_case format
- [ ] 361 | WARNING | This comment is 63% valid code; is this commented out code?
- [ ] 367 | ERROR   | Method name "breakpointIdentifier" in class DoubleClickAdSlot is not in snake case format, try "breakpoint_identifier"
- [ ] 375 | ERROR   | Method name "hasMapping" in class DoubleClickAdSlot is not in snake case format, try "has_mapping"
- [ ] 384 | ERROR   | Variable "DoubleClick" is not in valid snake_case format
- [ ] 397 | ERROR   | Variable "breakpointIdentifier" is not in valid snake_case format
- [ ] 398 | ERROR   | Variable "DoubleClick" is not in valid snake_case format
- [ ] 398 | ERROR   | Variable "breakpointIdentifier" is not in valid snake_case format
- [ ] 401 | ERROR   | Variable "browserHeight" is not in valid snake_case format
- [ ] 402 | ERROR   | Variable "browserWidth" is not in valid snake_case format
- [ ] 402 | ERROR   | Object property "minWidth" is not in valid snake_case format
- [ ] 404 | ERROR   | Variable "sizeStrings" is not in valid snake_case format
- [ ] 405 | ERROR   | Variable "sizeArray" is not in valid snake_case format
- [ ] 407 | ERROR   | Variable "sizeStrings" is not in valid snake_case format
- [ ] 412 | ERROR   | Variable "sizeArray" is not in valid snake_case format
- [ ] 414 | WARNING | This comment is 64% valid code; is this commented out code?
- [ ] 419 | ERROR   | Variable "browserWidth" is not in valid snake_case format
- [ ] 419 | ERROR   | Variable "browserHeight" is not in valid snake_case format
- [ ] 420 | ERROR   | Variable "sizeArray" is not in valid snake_case format
- [ ] 442 | ERROR   | Member variable "minWidth" is not in valid snake_case format.
- [ ] 449 | ERROR   | Member variable "maxWidth" is not in valid snake_case format.
- [ ] 461 | ERROR   | Object property "minWidth" is not in valid snake_case format
- [ ] 465 | ERROR   | Object property "maxWidth" is not in valid snake_case format
- [ ] 480 | ERROR   | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$this'

**FILE: DoubleClick-for-WordPress/dfw-options.php**

- [ ] 27 | ERROR   | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '__'
- [ ] 54 | WARNING | This comment is 70% valid code; is this commented out code?
- [ ] 62 | WARNING | This comment is 70% valid code; is this commented out code?
- [ ] 70 | WARNING | This comment is 70% valid code; is this commented out code?
- [ ] 79 | WARNING | This comment is 69% valid code; is this commented out code?
- [ ] 88 | WARNING | This comment is 69% valid code; is this commented out code?
- [ ] 110 | ERROR   | Variable "DoubleClick" is not in valid snake_case format
- [ ] 112 | ERROR   | Variable "DoubleClick" is not in valid snake_case format
- [ ] 112 | ERROR   | Object property "networkCode" is not in valid snake_case format
- [ ] 113 | ERROR   | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$DoubleClick'
- [ ] 113 | ERROR   | Variable "DoubleClick" is not in valid snake_case format
- [ ] 113 | ERROR   | Object property "networkCode" is not in valid snake_case format
- [ ] 115 | ERROR   | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not 'get_option'
- [ ] 120 | ERROR   | Variable "DoubleClick" is not in valid snake_case format
- [ ] 122 | ERROR   | Variable "DoubleClick" is not in valid snake_case format
- [ ] 124 | ERROR   | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$b'
- [ ] 125 | ERROR   | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$b'
- [ ] 125 | ERROR   | Object property "minWidth" is not in valid snake_case format
- [ ] 126 | ERROR   | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$b'
- [ ] 126 | ERROR   | Object property "maxWidth" is not in valid snake_case format
- [ ] 137 | ERROR   | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$identifier'
- [ ] 144 | ERROR   | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$min_width'
- [ ] 151 | ERROR   | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$max_width'

**FILE: DoubleClick-for-WordPress/dfw-widget.php**

- [ ] 29 | ERROR | Variable "DoubleClick" is not in valid snake_case format
- [ ] 45 | ERROR | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '__'
- [ ] 58 | ERROR | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$args'
- [ ] 62 | ERROR | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$args'
- [ ] 62 | ERROR | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not 'apply_filters'
- [ ] 62 | ERROR | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$args'
- [ ] 66 | ERROR | Variable "DoubleClick" is not in valid snake_case format
- [ ] 68 | ERROR | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$args'
- [ ] 80 | ERROR | Variable "DoubleClick" is not in valid snake_case format
- [ ] 85 | ERROR | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$this'
- [ ] 85 | ERROR | Expected next thing to be an escaping function (like esc_html_e() or esc_attr_e()), not '_e'
- [ ] 86 | ERROR | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$this'
- [ ] 86 | ERROR | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$this'
- [ ] 89 | ERROR | Variable "DoubleClick" is not in valid snake_case format
- [ ] 93 | ERROR | Variable "DoubleClick" is not in valid snake_case format
- [ ] 95 | ERROR | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$b'
- [ ] 95 | ERROR | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$b'
- [ ] 95 | ERROR | Object property "minWidth" is not in valid snake_case format
- [ ] 99 | ERROR | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$this'
- [ ] 99 | ERROR | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$b'
- [ ] 100 | ERROR | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$instance'
- [ ] 115 | ERROR | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$this'
- [ ] 116 | ERROR | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$instance'
- [ ] 127 | ERROR | Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$this'
