### ISSUE TITLE
PHP warning in DFW widget

### ISSUE THREAD

**Issue by 0aveRyan** [INN/DoubleClick-for-WordPress#6]
<img width="364" alt="screen shot 2015-08-05 at 1 55 26 pm" src="https://cloud.githubusercontent.com/assets/9565066/9095471/3624943c-3b6c-11e5-9772-19d5d2834873.png">

https://github.com/INN/DoubleClick-for-WordPress/blob/master/dfw-widget.php#L99

**Comment by benlk** [comment]
This doesn't apply to the current-`master` version of the widget.
